CREATE USER EC_proyect_admin IDENTIFIED BY 1234 QUOTA UNLIMITED ON USERS;
CREATE USER EC_proyect_invit IDENTIFIED BY 4321 QUOTA UNLIMITED ON USERS;

--Creamos los roles
CREATE ROLE ROL_ADMIN;
CREATE ROLE ROL_INVITADO;

GRANT CONNECT, CREATE SESSION TO ROL_INVITADO;
GRANT ALL PRIVILEGES TO ROL_ADMIN;

GRANT ROL_ADMIN TO EC_proyect_admin;
GRANT ROL_INVITADO TO EC_proyect_invit;
