CREATE SEQUENCE shospital
INCREMENT BY 1
  START WITH 1
  MAXVALUE 1
  MINVALUE 1
  CYCLE
  NOCACHE;

CREATE SEQUENCE spersona
  INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    CYCLE
    NOCACHE;

CREATE SEQUENCE sedos
  INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    CYCLE
    NOCACHE;

CREATE SEQUENCE smarca
  INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    CYCLE
    NOCACHE;

CREATE SEQUENCE smodelo
  INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    CYCLE
    NOCACHE;

CREATE SEQUENCE sseguro
  INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    CYCLE
    NOCACHE;

CREATE SEQUENCE scliente
  INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    CYCLE
    NOCACHE;

CREATE SEQUENCE scotizacion
  INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    CYCLE
    NOCACHE;

CREATE SEQUENCE spago
  INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    CYCLE
    NOCACHE;

CREATE SEQUENCE spoliza
  INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    CYCLE
    NOCACHE;

CREATE SEQUENCE ssiniestro
  INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    CYCLE
    NOCACHE;

CREATE SEQUENCE ss_colision
  INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    CYCLE
    NOCACHE;

CREATE SEQUENCE ss_social
  INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    CYCLE
    NOCACHE;

CREATE SEQUENCE ss_materiañ
  INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    CYCLE
    NOCACHE;

CREATE SEQUENCE spago_tarj
  INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    CYCLE
    NOCACHE;
